# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('plansza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
