# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 11:52
from __future__ import unicode_literals

from django.db import migrations, models

import plansza.models


class Migration(migrations.Migration):
    dependencies = [
        ('plansza', '0002_event_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(default=plansza.models.get_random_photo),
        ),
        migrations.AlterField(
            model_name='event',
            name='facebook_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
