# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 13:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('plansza', '0004_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
