# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import social.apps.django_app.default.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plansza', '0005_auto_20160409_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_data',
            field=social.apps.django_app.default.fields.JSONField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='eventhour',
            name='time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
