# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import social.apps.django_app.default.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plansza', '0005_auto_20160409_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_data',
            field=social.apps.django_app.default.fields.JSONField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='eventhour',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 13, 42, 17, 691046, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
