# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plansza', '0007_auto_20160409_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
