# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plansza', '0008_event_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
