# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 06:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plansza', '0009_friend_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevents',
                                            to='plansza.Event')),
                ('users', models.ManyToManyField(blank=True, related_name='subevents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
